name: Release

on:
  push:
    tags:
      - '*'

env:
  NODE_VERSION: 14.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Update Version Number
        run: |
          find . -name package.json -exec sed -i "s/\"version\": \"0.0.0-CURO\",/\"version\": \"${{ steps.get_version.outputs.VERSION }}\",/g" {} \;

      - run: npm ci
      - run: npm run build.libs
      - run: echo "${{secrets.NPMRC}}" >> ~/.npmrc
      - run: npm publish
        working-directory: dist/core
